Feature/data in models
Leboroz/blog-app pull request #4
Opened 2022-05-02 19:42 UTC by Leboroz

# Learning objectives

- Set up associations between models.
- Write SQL queries with Active Record.

<img src="https://media4.giphy.com/media/QhmboW0R7eUbm/giphy.gif"/>

## Description

> Now it's time to set up our models. To start with, we have tables for Users, Posts, Comments, and Likes, which means we need a model for each one. You've already set the foreign key in the table schema but be sure to write it here too!

2022-05-02 19:55 UTC, mikethreels requested changes
Hi Leo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-02 19:55 UTC, mikethreels commented on app/models/user.rb
> +  has_many :likes
- [ ] you need to set the foreign key as well for the association

2022-05-02 19:55 UTC, mikethreels commented on app/models/user.rb
> +  end
- [ ] to be sure you're getting the correct posts you should order them first, which will look something like the below.
```
posts.order('created_at Desc').limit(3)
```

2022-05-02 19:55 UTC, mikethreels commented on app/models/post.rb
> +    User.find_by(id: user.id).update(post_counter: user.post_counter.nil? ? 1 : ++user.post_counter)
- [ ] if you set the foreign key in the `User` model and set the belongs to in this model to the foreign and class_name: user the following can look like below ```  author.increment!(:posts_counter)```
- [ ] [OPTIONAL]after that you can also add something like `after_save :update_post_counter` and make this method private

2022-05-02 19:55 UTC, mikethreels commented on app/models/post.rb
> +  end
- [ ] to be sure you're getting the correct comments you should sort them first, which will look something like the below.
```
def recent_comments
  comments.order('created_at Desc').limit(5)
end

```

2022-05-02 19:55 UTC, mikethreels commented on app/models/comment.rb
> +  end
- [ ] in this model you can do the same as I suggested in the user model

2022-05-02 19:55 UTC, mikethreels commented on app/models/like.rb
> +  end
- [ ] in this model you can do the same as I suggested in the user model

2022-05-03 19:13 UTC, Deepakdanger approved these changes
Hi @Leboroz, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 19:57 UTC, closed without merging