Feature/views
Leboroz/blog-app pull request #5
Opened 2022-05-04 18:38 UTC by Leboroz

# Learning objectives

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.

<img src="https://media2.giphy.com/media/3o6Mbnll2gudglC3HG/giphy.gif"/>

## Description

- In this project, you will be adding the Views associated with the Models and Controllers you've already created for your Blog App.

2022-05-04 21:06 UTC, Gambit142 requested changes
Hi @Leboroz 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-04 21:06 UTC, Gambit142 commented on app/controllers/posts_controller.rb
- [x] There is a syntax error here, the code should be `@path = helpers.user_post_path(:id)`. Kindly fix it. 👍

2022-05-04 21:06 UTC, Gambit142 commented on app/controllers/users_controller.rb
> +
- [x] There is a syntax error here, the code should be `@path = helpers.user_posts_path(:id)`. Kindly fix it. 👍

2022-05-04 21:06 UTC, Gambit142 commented on app/views/users/index.html.erb
> +  <%end%>
- [x] When I click on a user, the page should direct me to the `show` page for a user. Currently, I have to manually type in the URL to show me the `show` page for a user. Kindly fix it. 👍

2022-05-04 21:06 UTC, Gambit142 commented on app/controllers/posts_controller.rb
> +    @path = helpers.user_post_path(id:)
- [x] When I click all posts, I get an error that says it can't find the id of the `User`. Kindly ensure that it links to the `post#index` page. 👍

2022-05-04 21:06 UTC, Gambit142 commented on app/views/posts/index.html.erb
> +      <% end %>
- [x] Kindly render `posts.most_recent_comments` here instead of `post.comments`.

2022-05-05 01:04 UTC, Leboroz commented on app/controllers/posts_controller.rb
This breaks the code. it sends to ``/users/id/posts`` it seems that   **:id = "id"**

2022-05-05 01:59 UTC, andersonlebon requested changes
## Hi @Leboroz 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 01:59 UTC, andersonlebon commented on app/controllers/posts_controller.rb
> +    @path = helpers.user_post_path(id:)
![image](https://user-images.githubusercontent.com/65068771/166853117-ae8dd504-bf21-4837-b3f8-942e502e40b9.png)

- [ ] kindly you not that you still have a syntax error here. Kindly make sure you solve it. The `user_id` you are trying to access is in the params, as you added a method for getting it(`def id`) you need to call it as a method(`id`).
- [ ] Note that also this path is incorrect, it should be `user_posts_path`

  Hint :point_down: 

```rb
@path = helpers.user_posts_path(id)
```

2022-05-05 03:00 UTC, rloterh requested changes
Hi Leo, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have an appropriate ReadMe.
Kindly note that _ReadMe_ is mostly the first place that visitors of this project's repository will go and therefore it has to be very detailed and professional. Also, it needs to be done well with respect to this capstone project,  which will likely feature in your portfolio. Therefore, kindly ensure to improve upon these aspects of your ReadMe:
- [ ] _How to run and test this project_ **should be detailed, clear, and well-organized**.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-05 04:05 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Leo, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comment(s) marked **[OPTIONAL]** under this review_
<br>
Cheers and Happy coding!👏 💻 🍷 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 04:05 UTC, rloterh commented on app/assets/stylesheets/users.scss
> +
- [ ] OPTIONAL
One of your pages does not match the given [wireframe templates](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md), considering the route `http://[::1]:3000/users/1/posts/1`. Kindly note we as much as possible want our design to closely match the given template. Kindly endeavor to improve upon your styling to match the given template.

**The original wireframe:**
![image](https://user-images.githubusercontent.com/12745474/166861891-4052da6d-6836-4389-9a88-fe908c35a195.png)


**Your design:**
![image](https://user-images.githubusercontent.com/12745474/166861929-6334bf98-13a1-47aa-ad26-f614bd475f4d.png)

2022-05-05 14:24 UTC, closed without merging